### ISSUE TITLE
nmap-service-probes 文件中的 pcre 正则语句与 python 自带正则引擎是否完全兼容。

### ISSUE THREAD

**Issue by moonD4rk** [boy-hack/nmap-parser#1]
nmap-service-probes 中用来匹配返回信息的正则表达式 `match` 字段，使用的是 PCRE 语法，Python 自带的 `re` 引擎不支持所有的 PCRE 语法，在匹配某些返回时可能会有一定的误报和漏报，此处是不是需要优化处理一下。

**Comment by boy-hack** [comment]
比如哪些不兼容呢？转出的是json，想的不只是python，其他语言例如go都可以调用
